### ISSUE TITLE
TclError: bitmap "icon.ico" not defined

### ISSUE THREAD

**Issue by PatricioUQ** [PaulRitsche/DeepACSA#26]
HI Paul,

Great job with DeepACSA!

I am trying install and run your software but found an error I suppose is related with the icon of used in the gui:

`(base) PS C:\QuantitativeUS\DeepACSA> & C:/ProgramData/Anaconda3/python.exe c:/QuantitativeUS/DeepACSA/DeepACSA_tkinter.TclError: bitmap "icon.ico" not defined
(base) PS C:\QuantitativeUS\DeepACSA> conda activate base
(base) PS C:\QuantitativeUS\DeepACSA> & C:/ProgramData/Anaconda3/python.exe c:/QuantitativeUS/DeepACSA/DeepACSA/deep_acsa_gui.py
Traceback (most recent call last):
  File "c:\QuantitativeUS\DeepACSA\DeepACSA\deep_acsa_gui.py", line 351, in <module>
    DeepACSA(root)
  File "c:\QuantitativeUS\DeepACSA\DeepACSA\deep_acsa_gui.py", line 36, in __init__
    root.iconbitmap("icon.ico")
  File "C:\ProgramData\Anaconda3\lib\tkinter\__init__.py", line 2080, in wm_iconbitmap    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)_tkinter.TclError: bitmap "icon.ico" not defined`

I also had some issues with some gui_helpers, it seems that the new version of Tensorflow has changed where "img_to_array" lives. 

`Loading personal and system profiles took 2294ms.
(base) PS C:\QuantitativeUS\DeepACSA> conda activate base
(base) PS C:\QuantitativeUS\DeepACSA> & C:/ProgramData/Anaconda3/python.exe c:/QuantitativeUS/DeepACSA/DeepACSA/deep_acsa_gui.py
Traceback (most recent call last):  File "c:\QuantitativeUS\DeepACSA\DeepACSA\deep_acsa_gui.py", line 11, in <module>    import gui_helpers      
  File "c:\QuantitativeUS\DeepACSA\DeepACSA\gui_helpers\__init__.py", line 10, in <module>
    from gui_helpers.predict_muscle_area import *
  File "c:\QuantitativeUS\DeepACSA\DeepACSA\gui_helpers\predict_muscle_area.py", line 20, in <module>
    from keras.preprocessing.image import img_to_array
ImportError: cannot import name 'img_to_array' from 'keras.preprocessing.image' (C:\ProgramData\Anaconda3\lib\site-packages\keras\preprocessing\image.py)`

I managed to sort this "'img_to_array' error out but not sure if my .ico error is because of me and my environment installation or something else that has to be updated in the code.

Sorry if these are fairly naïve questions but I am new at Python.

Cheers,

PPM

**Comment by PaulRitsche** [comment]
Hi Patricio, 

thanks for opening the issue, your questions are not naive!
Here are the solutions for your errors: 

1. The first error with the .ico file can be solved by fetching / pulling the Github repo anew. The reason for this is, to be honest, that the .ico file got lost in the release somehow. This was entirely my mistake, sorry for that. 

2. The second error should not occur when using the TF version that we specified in the environment.yml / requirements.txt file. I don't know about the newer versions, I haven't tested those yet. 

Hope that helps and if there is anything else just let know. 

Cheers, 
Paul

**Comment by PaulRitsche** [comment]
* Regarding error 1: You can just download the .ico file and put in the same folder as the deep_acsa_gui.py, that does the trick as well and won't involve all other files.

**Comment by PatricioUQ** [comment]
Thanks Paul, I had a root directory problem that I got fixed with your hints. 

Cheers,

Patricio
